# Site settings
title: Ridgeline Labs Inc.
email: hzhou1995@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  We are Ridgeline Labs Inc., an AR/VR games company. We create compelling and fun experiences for the latest augmented and virtual reality platforms, such as the HTC Vive.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
